n = input('digite algo: ')
print('O tipo primitivo desse input é: {}'.format(type(n)))
print('é um numero? {}'.format(n.isnumeric()))
print('é alfabético? {}'.format(n.isalpha()))
print('é alfanumerico? {}'.format(n.isalnum()))
print('é um codigo ascii? {}'.format(n.isascii()))
print('é um dígito? {}'.format(n.isdigit()))
print('é um decimal? {}'.format(n.isdecimal()))
print('é minúsculo? {}'.format(n.islower()))
print('é maiúsculo? {}'.format(n.isupper()))
print('é um identificador? {}'.format(n.isidentifier()))
print('é um imprimível? {}'.format(n.isprintable()))
print('só tem espaços? {}'.format(n.isspace()))
print('esta capitalizado? {}'.format(n.istitle()))
