nome = str(input('Digite seu nome completo: ')).strip()
print(nome.upper())
print(nome.lower())
nomes = nome.split()
# nomev = ''.join(nomes)
# print('O seu nome todo tem {} letras'.format(len(nomev)))
print('O seu nome todo tem {} letras'.format(len(nome) - nome.count(' ')))
# print('O seu primeiro nome tem {} letras'.format(nome.find(' ')))
print('O seu primeiro nome é {} e ele tem {} letras'.format(nomes[0], len(nomes[0])))
