print('='*30)
print('{:^30}'.format('BANCO CEV'))
print('='*30)
n = int(input('QUal Valor você quer sacar? R$ '))
print(f'Total de {n // 50} cedulas de R$50')
print(f'Total de {(n % 50) // 20} cedulas de R$20')
print(f'Total de {((n % 50) % 20) // 10} cedulas de R$10')
print(f'Total de {(((n % 50) % 20) % 10) // 1} cedulas de R$1')
print('=='*30)
print('Volte sempre ao banco CEV! Tenha um bom dia!')